### ISSUE TITLE
GESI.getClientInternal is not a function

### ISSUE THREAD

**Issue by Xafenn** [StarShip-Avalon-Projects/EveProjects#5]
EveQueue sheet by Absolute Truth v.3.1:
GESI library version 41, error message "GESI.getClientInternal is not a function"

Sheet was on GESI version 35. When move back to GESI 35 on the sheet, the wrapper and sheet function as normal. Unknown if issue is missing function from wrapper, or EveQueue sheet issue.

**Comment by Gerolkae** [comment]
Defiantly a missing function. I need to research this one further.

**Comment by Gerolkae** [comment]
I don't see that function in the current version of GESI.
In Case it's a typo on my part.. delete the wrappers and replace them with a fresh copy.

Custom functions are beyond the scope of these wrappers. 

I don't have access to EveQueue and can't do anything with it.
